# Generated by Django 4.2.14 on 2024-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_workcompletionform_image_workcompletionform_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workcompletionform",
            name="first_aid_cases",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workcompletionform",
            name="lost_time_incidents",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="workcompletionform",
            name="medical_treatment_cases",
            field=models.IntegerField(default=0),
        ),
    ]
