# Generated by Django 4.2.14 on 2024-07-16 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_alter_workcompletionform_first_aid_cases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcompletionform",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
