# Generated by Django 4.2.14 on 2024-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0005_rename_location_toolboxtalkform_site_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolboxtalkform",
            name="toolbox_talk",
            field=models.IntegerField(default=1),
        ),
    ]
