# Generated by Django 4.2.14 on 2024-07-12 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpi",
            old_name="target",
            new_name="target_value",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="actual",
        ),
        migrations.RemoveField(
            model_name="kpi",
            name="user",
        ),
        migrations.AlterField(
            model_name="kpi",
            name="period",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
