# Generated by Django 4.2.14 on 2024-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0002_rename_target_kpi_target_value_remove_kpi_actual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="period",
        ),
        migrations.AddField(
            model_name="kpi",
            name="Objective",
            field=models.CharField(
                choices=[
                    ("Improve Control of Work (Cow)", "Improve Control of Work (Cow)"),
                    (
                        "Improve Behaviour Based Safety and Culture",
                        "Improve Behaviour Based Safety and Culture",
                    ),
                    ("Maintain Workplace Controls", "Maintain Workplace Controls"),
                    ("Improve Emergency Response", "Improve Emergency Response"),
                    (
                        "Comply with Legal Requirements)",
                        "Comply with Legal Requirements)",
                    ),
                    (
                        "Protect life, Property and Environment",
                        "Protect life, Property and Environment",
                    ),
                    ("Reduce Incident Rates", "Reduce Incident Rates"),
                    (
                        "Continually improve the HSSE Management System",
                        "Continually improve the HSSE Management System",
                    ),
                ],
                default="Improve Control of Work (Cow)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="actual_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
