# Generated by Django 4.2.14 on 2024-07-16 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0003_remove_kpi_period_kpi_objective_kpi_actual_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
