# Generated by Django 4.2.14 on 2024-07-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0004_kpi_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="actual_value",
        ),
    ]
