# Generated by Django 4.2.14 on 2024-07-11 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("Vivo", "Vivo"),
                            ("Goil", "Goil"),
                            ("Total Energy", "Total Energy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("Potential Incident", "Potential Incident"),
                            ("Near Miss", "Near Miss"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("Safety", "Safety"),
                            ("Health", "Health"),
                            ("Environment", "Environment"),
                            ("Security", "Security"),
                            ("Reputation", "Reputation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("immediate_action", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Close", "Close")],
                        default="Open",
                        max_length=10,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
